server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data_base_store
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true


  resources:
    add-mappings=true:logging:
  level:
    org:
      hibernate:
        type: trace